// Local SVG map enhancement. All coordinates, paths and links are pre-rendered.
(()=>{'use strict';const map=document.querySelector('[data-case-map]');if(!map)return;
 const svg=map.querySelector('.world-map'),points=[...map.querySelectorAll('[data-location]')],tooltip=map.querySelector('.map-location-tooltip'),surface=map.querySelector('.map-geography'),controls=map.querySelector('.map-scale-controls');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),limits={world:1000,min:5,local:80,region:600};let active=null,visible=false;
 const view=()=>svg.getAttribute('viewBox').split(' ').map(Number);
 const zoom=v=>map.dispatchEvent(new CustomEvent('map-zoom-request',{detail:v}));
 function sync(){const width=view()[2],unit=width/svg.getBoundingClientRect().width;map.dataset.mapLevel=width<=limits.local?'local':width<limits.region?'regional':'world';for(const p of points){const [vx,vy,vw,vh]=view(),[px,py]=p.getAttribute('transform').match(/[\d.-]+/g).map(Number),inside=px>=vx&&px<=vx+vw&&py>=vy&&py<=vy+vh;p.style.display=inside?'':'none';p.setAttribute('tabindex',inside?'0':'-1');p.setAttribute('aria-hidden',String(!inside));for(const [cls,size] of [['location-hit',22],['location-halo',6],['location-dot',3.5]])p.querySelector('.'+cls).setAttribute('r',unit*size);}}
 function position(x,y){const r=surface.getBoundingClientRect(),b=tooltip.getBoundingClientRect();tooltip.style.left=Math.max(8,Math.min(r.width-b.width-8,x-r.left+14))+'px';tooltip.style.top=Math.max(8,Math.min(r.height-b.height-8,y-r.top+14))+'px';}
 function show(point,event){active=point;map.querySelectorAll("[data-location-result]").forEach(p=>p.classList.toggle("is-active",p.dataset.locationResult===point.dataset.location));points.forEach(p=>p.classList.toggle('is-active',p===point));map.querySelectorAll('[data-nearby]').forEach(p=>p.classList.toggle('is-active',p.dataset.nearby===point.dataset.location));tooltip.replaceChildren();const strong=document.createElement('strong'),code=document.createElement('span'),hint=document.createElement('small');strong.textContent=point.dataset.city;code.textContent=point.dataset.location;hint.textContent=point.dataset.destination;tooltip.append(code,strong,hint);tooltip.hidden=false;const r=point.querySelector('.location-dot').getBoundingClientRect();position(event?.clientX??r.x+r.width/2,event?.clientY??r.y+r.height/2);}
 function hide(){active=null;tooltip.hidden=true;map.querySelectorAll('.map-location.is-active,.map-nearby-track.is-active').forEach(p=>p.classList.remove('is-active'));}
 for(const point of points){point.addEventListener('pointerenter',e=>show(point,e));point.addEventListener('pointermove',e=>position(e.clientX,e.clientY));point.addEventListener('pointerleave',()=>{if(document.activeElement!==point)hide();});point.addEventListener('focus',()=>show(point));point.addEventListener('blur',hide);point.addEventListener('keydown',e=>{if(e.key==='Escape'){hide();point.blur();}});}
 for(const button of map.querySelectorAll('[data-location-zoom]'))button.addEventListener('click',()=>{const point=points.find(p=>p.dataset.location===button.dataset.locationZoom);zoom(point.dataset.locationViewport.split(' ').map(Number));hide();setTimeout(()=>{point.focus({preventScroll:true});show(point);},450);});
 for(const button of controls.querySelectorAll('button'))button.addEventListener('click',()=>{hide();if(button.dataset.mapScale==='reset'){zoom([0,0,1000,500]);return;}const [x,y,w,h]=view(),next=Math.max(limits.min,Math.min(limits.world,w*(button.dataset.mapScale==='in'?.5:2)));zoom([Math.max(0,Math.min(1000-next,x+w/2-next/2)),Math.max(0,Math.min(500-next/2,y+h/2-next/4)),next,next/2]);});
 function lifecycle(){map.classList.toggle('map-motion-paused',reduced.matches||document.hidden||!visible);}
 new IntersectionObserver(es=>{visible=es.some(e=>e.isIntersecting);lifecycle();}).observe(map);reduced.addEventListener('change',lifecycle);document.addEventListener('visibilitychange',lifecycle);
 map.addEventListener('map-view-change',()=>{sync();if(active)show(active);});new ResizeObserver(sync).observe(svg);controls.hidden=false;map.classList.add('map-locations-ready');sync();
})();
