// Only public, allowlisted editorial sources enter the build. No private lookups.
const capabilities=require('../src/content/rail-capabilities.json');
const seed=require('../src/content/rail-cases.public.json');
const links=require('../src/content/rail-links.json');
const geography=require('../src/content/rail-map.json');
const mapComponents=require('./rail-map-components.cjs');
const caseMedia=require('../src/content/rail-case-media.json');
const publicKeys=new Set(['id','title','sourceTitle','sourceId','url','summary','scopeFact','tags','capabilityIds','region','geographyPrecision','locationLabel','featured','latitude','longitude','customerName','operatorName','currentDeliveryStatus','imagePath','sourceBasis','geoRule','copyStatus','httpStatus']);
for(const record of seed.cases){
  for(const key of Object.keys(record))if(!publicKeys.has(key))throw Error(`Unexpected public case field: ${key}`);
  for(const key of ['latitude','longitude','customerName','operatorName','currentDeliveryStatus','imagePath'])if(record[key]!==null)throw Error(`Public v0.10 disallows ${key}`);
  if(record.region&&!geography.regions.some(r=>r.id===record.region))throw Error('Unknown public region');
  if(!record.url.startsWith('https://www.psa.inc/success-stories/'))throw Error('Unexpected case destination');
}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const tags=c=>`<ul class="case-tags" aria-label="Scope">${c.tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`;
function caseGraphic(record){
 const media=caseMedia[record.id];if(!media)throw Error('Missing case media: '+record.id);
 return '<figure class="case-graphic"><img src="../assets/'+media.asset+'-1024.webp" srcset="../assets/'+media.asset+'-512.webp 512w, ../assets/'+media.asset+'-1024.webp 1024w" sizes="(max-width:760px) calc(100vw - 40px), (max-width:1050px) 45vw, 410px" width="1024" height="476" loading="lazy" decoding="async" alt="'+esc(media.alt)+'"></figure>';
}
function caseCard(record){return `<article class="rail-case" id="case-${record.id}" data-case-id="${record.id}" data-case-region="${record.region||'unknown'}">${caseGraphic(record)}<div class="case-body"><p class="case-location">${esc(record.locationLabel)}</p><h3>${esc(record.title)}</h3><p>${esc(record.summary)}</p>${record.scopeFact?`<p class="case-fact">${esc(record.scopeFact)}</p>`:''}${tags(record)}<a class="text-link" href="${esc(record.url)}">Read case study <span class="sr-only">— ${esc(record.title)}</span><i data-lucide="arrow-right"></i></a></div></article>`;}
function map(){
 const regions=geography.regions.map(r=>`<g data-map-region="${r.id}" data-map-viewport="${r.viewport.join(' ')}"><path class="region-shape" d="${r.path}"/><g class="region-label" transform="translate(${r.labelAnchor.join(' ')})"><circle r="88" class="map-target"/><circle r="6"/><text y="-29" text-anchor="middle">${r.label}</text></g></g>`).join('');
 const options=seed.cases.map(c=>`<a href="#case-${c.id}" data-map-case="${c.id}" data-region="${c.region||'unknown'}">${esc(c.title)}</a>`).join('');
 const results=seed.cases.map(c=>`<article data-map-result="${c.id}" data-region="${c.region||'unknown'}"><p class="case-location">${esc(c.locationLabel)}</p><h4>${esc(c.title)}</h4><p>${esc(c.summary)}</p>${tags(c)}<a class="text-link" href="${esc(c.url)}">Read case study <span class="sr-only">— ${esc(c.title)}</span><i data-lucide="arrow-right"></i></a></article>`).join('');
 return `<div class="rail-map" data-case-map><div class="map-heading"><h3>Explore published project regions</h3><p>Explore project regions and selected city reference points. Nearby railway lines provide geographic context, not the extent of PSA’s work.</p></div>${mapComponents.controls()}<div class="map-filters" hidden aria-label="Filter published examples">${[['all','All examples'],['north-america','North America'],['china','China'],['unknown','Location not published']].map(([id,label])=>`<button type="button" data-map-filter="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><div class="map-layout"><div class="map-geography"><svg class="world-map" viewBox="0 0 1000 500" role="img" aria-label="Published case regions: North America and China; selected city reference points in the United States."><path class="map-land" d="${geography.landPath}"/>${regions}${mapComponents.layers()}${mapComponents.points()}</svg><div class="map-location-tooltip" hidden></div><button type="button" class="map-world-reset" data-map-world hidden>World view <i data-lucide="globe"></i></button></div><div class="map-explorer">${mapComponents.details()}<nav class="map-case-options" aria-label="Select a published example">${options}</nav><p class="map-status sr-only" role="status" aria-live="polite"></p><p class="map-empty" hidden>No published example in this selection. <button type="button" data-map-reset>View all case studies</button></p><div class="map-results">${results}</div></div></div>${mapComponents.alternatives()}</div>`;
}
function cards(){return capabilities.map((c,index)=>`<a class="rail-cap" data-capability="${c.id}" href="#${c.id}"><div class="card-top"><span>${String(index+1).padStart(2,'0')}</span>{{rail-icon:${c.icon}}}</div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><ul class="cap-examples">${c.examples.map(e=>`<li>${esc(e)}</li>`).join('')}</ul><span class="text-link">${esc(c.action)} <i data-lucide="arrow-right"></i></span></a>`).join('');}
function details(){return capabilities.map(c=>`<details class="capability-detail" id="${c.id}">${c.aliases.map(id=>`<span class="legacy-anchor" id="${id}" data-alias-for="${c.id}"></span>`).join('')}<summary>${esc(c.title)} <span aria-hidden="true">+</span></summary><div class="detail-body"><h3 tabindex="-1">${esc(c.detailHeading)}</h3><p class="detail-intro">${esc(c.intro)}</p><div class="detail-columns">${c.sections.map(s=>`<section><h4>${esc(s.label)}</h4>${s.items?`<ul>${s.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:`<p>${esc(s.text)}</p>`}</section>`).join('')}</div><div class="detail-related"><h4>${c.id==='expertise-monitoring'?'Product example':'Related published experience'}</h4>${c.id==='expertise-monitoring'?'<a href="#solutions">TraxSentinel Smart Advisor for level-crossing monitoring</a>':c.relatedCaseIds.map(id=>{const record=seed.cases.find(r=>r.id===id);return record?`<a href="${esc(record.url)}">${esc(record.sourceTitle)}</a>`:`<a href="${links.freightDispatching}">Rail Dispatching System for Heavy Rail Network in US</a>`;}).join('')}<a class="text-link" href="#contact">${esc(c.contact)} <i data-lucide="arrow-right"></i></a></div></div></details>`).join('');}
module.exports={expand:html=>html.replaceAll('{{rail-capabilities}}',cards()).replaceAll('{{rail-details}}',details()).replaceAll('{{rail-featured-cases}}',seed.cases.map((c,i)=>c.featured?caseCard(c,i):'').join('')).replaceAll('{{rail-more-cases}}',seed.cases.map((c,i)=>!c.featured?caseCard(c,i):'').join('')).replaceAll('{{rail-map}}',map()).replace(/\{\{rail-link:([^}]+)\}\}/g,(_,id)=>{if(!links[id])throw Error(`Unknown Rail link ${id}`);return esc(links[id]);})};
